// Credential-free installed-artifact setup proof. Run only in disposable Linux state.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
assert.equal(process.version, 'v24.16.0');
for (const key of ['CONCENTRATE_API_KEY', 'BL_API_KEY', 'CLAWHUB_AUTH_JSON']) assert.equal(process.env[key], undefined);
const variant = process.argv[2] ?? 'native'; assert.match(variant, /^native(?:-[a-z]+)?$/);
const proof = '/tmp/proof/' + variant; fs.mkdirSync(proof, { recursive: true });
const root = '/tmp/setup-v120-' + variant; fs.mkdirSync(root, { recursive: true });
const env = { PATH: process.env.PATH, HOME: root, OPENCLAW_STATE_DIR: root + '/state', OPENCLAW_CONFIG_PATH: root + '/config.json', SETUP_TEST_TOKEN: 'synthetic-setup-token-not-a-credential' };
const cli = '/tmp/host/node_modules/.bin/openclaw';
const commands = []; const records = [];
const save = (name, value) => fs.writeFileSync(`${proof}/${name}.json`, JSON.stringify(value, null, 2) + '\n');
const digest = raw => createHash('sha256').update(raw).digest('hex');
const configText = () => fs.readFileSync(env.OPENCLAW_CONFIG_PATH, 'utf8');
const config = () => JSON.parse(configText());
function run(label, args, expectedExit = 0) {
  const startedAt = new Date().toISOString();
  const r = spawnSync(cli, args, { env, cwd: root, encoding: 'utf8', timeout: 45000, maxBuffer: 8388608, detached: true });
  if (r.error || r.signal) { try { process.kill(-r.pid, 'SIGKILL'); } catch {} }
  const record = { label, args, startedAt, finishedAt: new Date().toISOString(), exitCode: r.status, signal: r.signal, stdout: r.stdout, stderr: r.stderr, error: r.error?.message };
  save(label, record); records.push(record); save('commands', records); commands.push({ label, args, startedAt, finishedAt: record.finishedAt, exitCode: r.status });
  assert.equal(r.status, expectedExit, `${label}: ${r.stderr || r.stdout || r.error?.message}`);
  return r.stdout;
}
try {
  run('install', ['plugins', 'install', '--force', '--accept-capabilities', '/tmp/candidate/concentrate-provider-1.2.0.tgz']);
  const listed = JSON.parse(run('plugin-list', ['plugins', 'list', '--json']));
  const plugin = listed.plugins.find(x => x.id === 'concentrate-provider');
  assert.equal(plugin.version, '1.2.0'); assert.equal(plugin.status, 'loaded'); assert.equal(plugin.enabled, true);
  assert.deepEqual(plugin.providerIds, ['concentrate']);
  const installedRoot = path.dirname(plugin.source);
  const expected = JSON.parse(fs.readFileSync('/tmp/proof/expected-files.json'));
  for (const file of expected) assert.equal(digest(fs.readFileSync(path.join(installedRoot, file.path))), file.sha256, file.path);
  const cfg = config();
  cfg.gateway = { ...cfg.gateway, mode: 'local', auth: { mode: 'token', token: '${SETUP_TEST_TOKEN}' } };
  cfg.env = { ...cfg.env, vars: { ...cfg.env?.vars, SETUP_SENTINEL: 'synthetic-config-sentinel' } };
  cfg.agents ??= {}; cfg.agents.defaults ??= {};
  cfg.agents.defaults.workspace = root + '/workspace';
  cfg.agents.defaults.model = { primary: 'openai/gpt-4.1-mini' };
  cfg.agents.defaults.models = { 'openai/gpt-4.1-mini': {}, 'concentrate/gpt-4.1-mini': { params: { temperature: 0.33 } } };
  cfg.plugins.entries['concentrate-provider'].config = { acknowledgeEstimatedCosts: true, costOverrides: { 'gpt-4.1-mini': { input: 11, output: 22, cacheRead: 3, cacheWrite: 4 } } };
  fs.writeFileSync(env.OPENCLAW_CONFIG_PATH, JSON.stringify(cfg, null, 2) + '\n');
  fs.mkdirSync(root + '/workspace', { recursive: true });
  const memory = root + '/workspace/MEMORY.md'; fs.writeFileSync(memory, 'Synthetic memory sentinel. Preserve exactly.\n');
  const memoryHash = digest(fs.readFileSync(memory));
  run('initial-validate', ['config', 'validate']);
  const before = config(); const originalHash = digest(configText());
  const offline = JSON.parse(run('models-offline', ['concentrate', 'models', '--json']));
  assert.equal(offline.source, 'bundled'); assert.equal(offline.count, 184); assert.equal(offline.models.length, 184);
  assert.equal(offline.models.some(x => x.id === 'redact-v1'), false);
  const live = JSON.parse(run('models-live', ['concentrate', 'models', '--refresh', '--json']));
  assert.equal(live.source, 'live');
  assert.deepEqual(live.models.map(x => x.id).sort(), offline.models.map(x => x.id).sort());
  const previewArgs = ['concentrate', 'setup', '--model', 'claude-haiku-4-5'];
  const preview = JSON.parse(run('preview', [...previewArgs, '--dry-run', '--json']));
  assert.equal(preview.canApply, true); assert.equal(preview.applied, false);
  assert.equal(digest(configText()), originalHash);
  const rejected = JSON.parse(run('wrong-review', [...previewArgs, '--apply', '--acknowledge-estimates', '--review', 'wrong', '--json'], 1));
  assert.equal(rejected.ok, false); assert.equal(digest(configText()), originalHash);
  const applied = JSON.parse(run('apply', [...previewArgs, '--apply', '--acknowledge-estimates', '--review', preview.plan.reviewToken, '--json']));
  assert.equal(applied.applied, true);
  const after = config();
  assert.deepEqual(after.plugins.entries['concentrate-provider'].config.costOverrides['claude-haiku-4-5'], preview.plan.costOverrides['claude-haiku-4-5']);
  assert.deepEqual(after.plugins.entries['concentrate-provider'].config.costOverrides['gpt-4.1-mini'], before.plugins.entries['concentrate-provider'].config.costOverrides['gpt-4.1-mini']);
  assert.deepEqual(after.agents.defaults.model, before.agents.defaults.model);
  assert.deepEqual(after.agents.defaults.models['concentrate/gpt-4.1-mini'], before.agents.defaults.models['concentrate/gpt-4.1-mini']);
  assert.ok(Object.hasOwn(after.agents.defaults.models, 'concentrate/claude-haiku-4-5'));
  assert.deepEqual(after.gateway.auth, before.gateway.auth); assert.deepEqual(after.env, before.env);
  assert.equal(digest(fs.readFileSync(memory)), memoryHash);
  run('after-validate', ['config', 'validate']);
  const freshPreview = JSON.parse(run('second-preview', [...previewArgs, '--dry-run', '--json']));
  const intervening = config(); intervening.env.vars.SETUP_SENTINEL = 'synthetic-concurrent-update'; fs.writeFileSync(env.OPENCLAW_CONFIG_PATH, JSON.stringify(intervening, null, 2) + '\n');
  const changedHash = digest(configText());
  JSON.parse(run('stale-review', [...previewArgs, '--apply', '--acknowledge-estimates', '--review', freshPreview.plan.reviewToken, '--json'], 1));
  assert.equal(digest(configText()), changedHash);
  env.CONCENTRATE_API_KEY = 'synthetic-only-not-a-real-key';
  const registered = JSON.parse(run('native-models', ['models', 'list', '--all', '--provider', 'concentrate', '--refresh', '--json']));
  assert.ok(registered.models.some(x => x.key === 'concentrate/claude-haiku-4-5' && x.available === true));
  delete env.CONCENTRATE_API_KEY;
  save('headless-summary', { passed: true, atUtc: new Date().toISOString(), version: '1.2.0', plugin: { id: plugin.id, status: plugin.status, trust: plugin.trust }, installedFilesMatched: expected.length, bundled: offline.count, live: live.count, headlessPreview: true, guardedApply: true, staleReviewRefused: true, primaryPreserved: true, envReferencePreserved: true, unselectedCostsPreserved: true, memoryPreserved: true, commands, paidInferenceRequests: 0 });
  const ttySpec = { cli, env, root, proof, configPath: env.OPENCLAW_CONFIG_PATH };
  fs.writeFileSync('/tmp/proof/tty-spec.json', JSON.stringify(ttySpec));
  const tty = spawnSync(process.execPath, ['/tmp/candidate/scripts/verification/setup-pty-1.2.0.mjs', '/tmp/proof/tty-spec.json'], { env: { PATH: process.env.PATH }, encoding: 'utf8', timeout: 135000, maxBuffer: 8388608 });
  save('tty-process', { status: tty.status, stdout: tty.stdout, stderr: tty.stderr, error: tty.error?.message });
  assert.equal(tty.status, 0, tty.stderr || tty.stdout);
  assert.equal(digest(fs.readFileSync(memory)), memoryHash);
  save('summary', { passed: true, atUtc: new Date().toISOString(), headless: true, tty: true, commands, paidInferenceRequests: 0 });
} catch (error) { save('failure', { message: error.message, commands, atUtc: new Date().toISOString() }); throw error; }
